### ISSUE TITLE
PSD Source File Cannot Open

### ISSUE THREAD

**Issue by iolson** [wdmtech/enviricons#2]
I'm getting a "Not a proper Photoshop File" when trying to open the PSD with Photoshop CS 5.1.

**Comment by wdmtech** [comment]
Hi @iolson, not sure how I missed this, I do apologise! 

I created the PSD with CS6 - I'm sure I selected to save it with compatibility mode... ~~I'll see if I can output a compatible file when I get to work on Monday (got a copy of CS5 there).~~ 

Check out [2.0.3](https://github.com/wdmtech/enviricons/releases/tag/2.0.3), I've uploaded a fresh copy :smile:

**Comment by wdmtech** [comment]
Thanks for bringing this to my attention, it seems the file was corrupted; it wouldn't even open in CC2014. Give the new release a spin, should be fine now. Feel free to re-open if not.
